/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWaybackRouteImport } from './routes/api/public/wayback'
import { Route as ApiPublicRecentRouteImport } from './routes/api/public/recent'
import { Route as ApiPublicInsightRouteImport } from './routes/api/public/insight'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaybackRoute = ApiPublicWaybackRouteImport.update({
  id: '/api/public/wayback',
  path: '/api/public/wayback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecentRoute = ApiPublicRecentRouteImport.update({
  id: '/api/public/recent',
  path: '/api/public/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInsightRoute = ApiPublicInsightRouteImport.update({
  id: '/api/public/insight',
  path: '/api/public/insight',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/insight': typeof ApiPublicInsightRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
  '/api/public/wayback': typeof ApiPublicWaybackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/insight': typeof ApiPublicInsightRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
  '/api/public/wayback': typeof ApiPublicWaybackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/insight': typeof ApiPublicInsightRoute
  '/api/public/recent': typeof ApiPublicRecentRoute
  '/api/public/wayback': typeof ApiPublicWaybackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/insight'
    | '/api/public/recent'
    | '/api/public/wayback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/insight' | '/api/public/recent' | '/api/public/wayback'
  id:
    | '__root__'
    | '/'
    | '/api/public/insight'
    | '/api/public/recent'
    | '/api/public/wayback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicInsightRoute: typeof ApiPublicInsightRoute
  ApiPublicRecentRoute: typeof ApiPublicRecentRoute
  ApiPublicWaybackRoute: typeof ApiPublicWaybackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wayback': {
      id: '/api/public/wayback'
      path: '/api/public/wayback'
      fullPath: '/api/public/wayback'
      preLoaderRoute: typeof ApiPublicWaybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recent': {
      id: '/api/public/recent'
      path: '/api/public/recent'
      fullPath: '/api/public/recent'
      preLoaderRoute: typeof ApiPublicRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/insight': {
      id: '/api/public/insight'
      path: '/api/public/insight'
      fullPath: '/api/public/insight'
      preLoaderRoute: typeof ApiPublicInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicInsightRoute: ApiPublicInsightRoute,
  ApiPublicRecentRoute: ApiPublicRecentRoute,
  ApiPublicWaybackRoute: ApiPublicWaybackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
